# Generated by Django 5.1.2 on 2024-12-17 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisPembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pembayaran', models.CharField(max_length=100)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Jenis Pembayaran',
                'verbose_name_plural': 'Jenis Pembayaran',
                'indexes': [models.Index(fields=['nama_pembayaran'], name='keuangan_je_nama_pe_cbb3f5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pembayaran', models.DateField()),
                ('jumlah_dibayar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('jenis_pembayaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keuangan.jenispembayaran')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.mahasiswa')),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran',
                'indexes': [models.Index(fields=['tanggal_pembayaran'], name='keuangan_pe_tanggal_44be18_idx'), models.Index(fields=['mahasiswa'], name='keuangan_pe_mahasis_ed74aa_idx'), models.Index(fields=['jenis_pembayaran'], name='keuangan_pe_jenis_p_e0f5bf_idx')],
            },
        ),
    ]
