# Generated by Django 5.1.2 on 2024-12-17 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JenisPembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pembayaran', models.CharField(max_length=100)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('keterangan', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pembayaran', models.DateField()),
                ('jumlah_dibayar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('jenis_pembayaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keuangan.jenispembayaran')),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.mahasiswa')),
            ],
        ),
    ]
