# Generated by Django 5.1.2 on 2024-12-17 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jenispembayaran',
            options={'verbose_name': 'Jenis Pembayaran', 'verbose_name_plural': 'Jenis Pembayaran'},
        ),
        migrations.AlterModelOptions(
            name='pembayaran',
            options={'verbose_name': 'Pembayaran', 'verbose_name_plural': 'Pembayaran'},
        ),
        migrations.AddIndex(
            model_name='jenispembayaran',
            index=models.Index(fields=['nama_pembayaran'], name='keuangan_je_nama_pe_cbb3f5_idx'),
        ),
        migrations.AddIndex(
            model_name='pembayaran',
            index=models.Index(fields=['tanggal_pembayaran'], name='keuangan_pe_tanggal_44be18_idx'),
        ),
        migrations.AddIndex(
            model_name='pembayaran',
            index=models.Index(fields=['mahasiswa'], name='keuangan_pe_mahasis_ed74aa_idx'),
        ),
        migrations.AddIndex(
            model_name='pembayaran',
            index=models.Index(fields=['jenis_pembayaran'], name='keuangan_pe_jenis_p_e0f5bf_idx'),
        ),
    ]
