# Generated by Django 5.1.2 on 2024-12-18 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jenispembayaran',
            name='jumlah',
        ),
    ]
