# Generated by Django 5.1.2 on 2024-12-17 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('akademik', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kehadiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertemuan_ke', models.IntegerField()),
                ('status_kehadiran', models.CharField(choices=[('HADIR', 'Hadir'), ('ALPHA', 'Alpha'), ('IZIN', 'Izin')], max_length=10)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.mahasiswa')),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.matakuliah')),
            ],
            options={
                'verbose_name': 'Kehadiran',
                'verbose_name_plural': 'Kehadiran',
                'indexes': [models.Index(fields=['mahasiswa', 'mata_kuliah'], name='laporan_keh_mahasis_3a30c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_akhir', models.DecimalField(decimal_places=2, max_digits=5)),
                ('keterangan', models.CharField(choices=[('LULUS', 'Lulus'), ('TIDAK LULUS', 'Tidak Lulus')], max_length=50)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.mahasiswa')),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.matakuliah')),
                ('tahun_akademik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akademik.tahunakademik')),
            ],
            options={
                'verbose_name': 'Nilai',
                'verbose_name_plural': 'Nilai',
                'indexes': [models.Index(fields=['mahasiswa', 'mata_kuliah', 'tahun_akademik'], name='laporan_nil_mahasis_b8566e_idx')],
            },
        ),
    ]
