# Generated by Django 5.1.2 on 2024-12-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matakuliah',
            options={'verbose_name': 'mata kuliah', 'verbose_name_plural': 'mata kuliah'},
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='kode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='nama',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='matakuliah',
            name='sks',
            field=models.IntegerField(null=True),
        ),
    ]
