# Generated by Django 5.1.2 on 2024-12-17 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0001_initial'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='dosen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.dosen'),
        ),
        migrations.DeleteModel(
            name='Dosen',
        ),
    ]
