# Generated by Django 5.1.2 on 2024-12-17 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0002_alter_jadwal_dosen_delete_dosen'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krs',
            name='mahasiswa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.mahasiswa'),
        ),
        migrations.DeleteModel(
            name='Mahasiswa',
        ),
    ]
