# Generated by Django 5.1.2 on 2024-12-17 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0003_alter_krs_mahasiswa_delete_mahasiswa'),
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matakuliah',
            name='prodi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.prodi'),
        ),
    ]
