# Generated by Django 5.1.2 on 2024-12-17 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akademik', '0003_alter_matakuliah_options_jadwal_dosen_jadwal_hari_and_more'),
        ('akademik', '0004_alter_matakuliah_prodi'),
    ]

    operations = [
    ]
